"""empty message

Revision ID: 076016c04aa6
Revises: b8f97b1df5f4
Create Date: 2024-02-28 19:08:46.525137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076016c04aa6'
down_revision = 'b8f97b1df5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
